### ISSUE TITLE
Aprendendo a fazer um docker-compose.yml

### ISSUE THREAD

**Issue by jaideraf** [vitorsilverio/libraryapi#97]
Estava tentando fazer um docker-compose.yml como ensinado naquele [vídeo que me enviou](https://youtu.be/zkMRWDQV4Tg?t=995), mas não consegui.

```yaml
version: '3.3'
services:
    app:
        build: .
        container_name: libraryapi
        command: uvicorn app.main:app --port 80 --reload
        ports:
            - '80:80'
        image: libraryapi:latest
        volumes:
            - .:/app
```
Quando faço o `docker-compose up --build` dá: 

```Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "uvicorn": executable file not found in $PATH: unknown```
